name: build-boxkit
on:
  workflow_dispatch: # allow manually triggering builds
  push:
    branches:
      - main
    paths-ignore: # don't rebuild on documentation change
      - '**.md'
      - LICENSE
  schedule:
    - cron: '43 8 * * *'

env:
  REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: fedora-toolbox-1password
  AUTH_SECRET: registry_auth_file

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        containerfile: 
          - egerlach-toolbox
    steps:
      - name: Computed environment variables
        run: |
          echo "FULL_IMAGE=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_ENV"
          
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # This step publishes a $REGISTRY_AUTH_FILE environment variable
      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ steps.registry_case.outputs.lowercase }}

      # Using secret for skopeo login as per: https://github.com/containers/image_build/blob/main/skopeo/README.md
      - name: Create secret from podman login
        run: |
          podman secret create ${{ env.AUTH_SECRET }} $REGISTRY_AUTH_FILE

      - name: Get base image version
        id: base_image
        run: |
          # Extract base image name from Containerfile
          BASE_IMAGE=$(grep -m1 FROM ContainerFiles/${{ matrix.containerfile }} | cut -d ' ' -f 2)
          echo "Base Image is: $BASE_IMAGE"
          echo "name=$BASE_IMAGE" >> "$GITHUB_OUTPUT"
          VERSION=$(.github/scripts/skopeo_inspect.sh --format "{{slice .Digest 7}}" docker://$BASE_IMAGE)
          echo "Base Image Version is: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set target tag
        id: target_tag
        run: |
          base_version=${{ steps.base_image.outputs.version }}
          sha=${{ github.sha }}
          TARGET_TAG=base-${base_version:0:10}-git-${sha:0:10}
          echo "Target Tag: $TARGET_TAG"
          echo "tag=$TARGET_TAG" >> "$GITHUB_OUTPUT"

      - name: Check if that version of this image exists
        id: check
        # Using secret for skopeo login as per: https://github.com/containers/image_build/blob/main/skopeo/README.md
        run: |
          if .github/scripts/skopeo_inspect.sh --format "{{.Name}}" docker://${{ env.FULL_IMAGE }}:${{ steps.target_tag.outputs.tag }}; then
            echo "Build already exists, skipping build."
            SHOULD_BUILD=false
          else
            echo "Build does not exist, buildingâ€¦"
            SHOULD_BUILD=true
          fi
          echo "should_build=$SHOULD_BUILD" >> "$GITHUB_OUTPUT"

      # Build metadata
      - name: Image Metadata
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        if: steps.check.outputs.should_build == 'true'
        id: meta
        with:
          flavor: |
            latest=true
          images: |
            ${{ matrix.containerfile }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/egerlach/toolbox/main/README.md
          tags: |
              type=schedule
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr
              type=raw,value=${{ steps.target_tag.outputs.tag }}


      - name: Buildah Action
        id: build_image
        if: steps.check.outputs.should_build == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./ContainerFiles/${{ matrix.containerfile }}
          image: ${{ matrix.containerfile }}
          tags: latest ${{ steps.target_tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: true

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps) }}"

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      # Sign container
      - name: Install cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0

      - name: Sign container image
        if: steps.check.outputs.should_build == 'true'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.lowercase }}/${{ matrix.containerfile }}@${TAGS}
        env:
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps) }}"
